# CafecaBackend Default Config

title = "CafecaBackend"

[base]
folder = "CafecaBE"
debug = false

[blockchain]

[database]

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /api/questions | Bot.FindCafeca.getQuestions",
  "get | /api/suggestion | Bot.FindCafeca.getSuggestion",
  "get | /api/store/:storeID | Bot.FindCafeca.getStore"
]